version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: contentservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build: .
    command: gunicorn contentService.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - backend
    environment:
      - DATABASE_URL=postgres://postgres:root@db:5432/contentservice

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
