# Generated by Django 5.1.3 on 2024-12-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_expensepriority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensepriority',
            old_name='expenseNamne',
            new_name='expenseName',
        ),
    ]
