# Generated by Django 5.1.3 on 2024-12-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_expensenamne_expensepriority_expensename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepriority',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
