# Generated by Django 5.1.3 on 2024-12-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_expensepriority_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensepriority',
            old_name='acquired',
            new_name='achieved',
        ),
    ]
