# Generated by Django 5.1.3 on 2024-12-04 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_acquired_expensepriority_achieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensepriority',
            old_name='priority',
            new_name='priorityLevel',
        ),
    ]
