# Generated by Django 5.1.3 on 2024-12-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_priority_expensepriority_prioritylevel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensepriority',
            old_name='expenseName',
            new_name='expense',
        ),
    ]
