# Generated by Django 5.1.3 on 2024-12-06 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_movies_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
