# Generated by Django 5.1.3 on 2024-12-13 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservedAt', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dateReserved', models.DateTimeField()),
                ('movie', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservedMovie', to='api.movie')),
                ('person', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservedTo', to='api.person')),
            ],
        ),
    ]
