# Generated by Django 5.1.3 on 2024-12-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='active', max_length=100),
            preserve_default=False,
        ),
    ]
