# Generated by Django 5.1.3 on 2024-12-16 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='person',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservedTo', to='api.person'),
        ),
    ]
