# Generated by Django 5.1.3 on 2024-12-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_reservation_movie'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('person', 'movie'), name='unique_reservation'),
        ),
    ]
